==================== LOADING DATASET ====================

Skipped 0 files due to NaNs/Infs.

==================== DATASET LOADED ====================


==================== SPLITTING DATASET ====================

Total samples: 71118
Train samples: 49782
Validation samples: 10667
Test samples: 10669

==================== DATASET SPLITTED ====================


==================== TRAINING STARTED ====================


=========== TRAIN LOADER ===========
Train batches: 1556
Validation batches: 334
Test batches: 334
Using device: cuda

===== Training with Batch Size: 32, Learning Rate: 0.0001 =====
self.encoder_type ECA

=== Training RawNet3 ===
/raid/m13521069/RawNets-PF/rawnet-pf/lib/python3.8/site-packages/torch/autograd/__init__.py:173: UserWarning: Error detected in StdBackward0. Traceback of forward call that caused the error:
  File "trainer_all_RawNet_waveform.py", line 106, in <module>
    train_rawnet3_with_loaders(model3, train_loader, val_loader,
  File "/raid/m13521069/RawNets-PF/classes/models/RawNets/RawNet3/trainer_RawNet3.py", line 40, in train_rawnet3_with_loaders
    outputs = model(inputs)
  File "/raid/m13521069/RawNets-PF/rawnet-pf/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/raid/m13521069/RawNets-PF/classes/models/RawNets/RawNet3/model_RawNet3_preprocessed.py", line 227, in forward
    s = torch.std(x, dim=-1, keepdim=True)
 (Triggered internally at  ../torch/csrc/autograd/python_anomaly_mode.cpp:102.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

==================== PREPROCESSING COMPLETED ====================

Total time taken: 6.52 seconds

===============================================================
